### PR TITLE
Revise the package to meet the new standard of R-release from cran

### PR DESCRIPTION
**Pull request by HJ08003**
Changed:
(1) Rd files are generated by Roxygen2 based on the Roxygen2 comments in the R files.
(2) C function registration revised.
(3) Remove the unused variable declaration in rand.c.

Tested:
(1) On examples in mnp.Rd to make sure the same results are produced using HJ08003/MNP vs kosukeimai/MNP.
* I have a shell script test.sh which installed the packages one at a time and ran the test.R. The diff on the results showed no difference.

(2) Travis-ci on both R versions, release and devel dated 4/29/2017.
 * Passed installation/building/checking:   
    https://travis-ci.org/HJ08003/MNP/builds/229263772
 * Tested on the examples in the package: 
    https://travis-ci.org/HJ08003/MNP/builds/229238763

### CODE REVIEW

**Comment by kosukeimai** [comment]
Do the vignettes get build automatically?

**Comment by HJ08003** [comment]
Yes. Here is the proof:


    pol-c07jw0gqf4mg:MNP hubertj$ R CMD build .

    pol-c07jw0gqf4mg:MNP hubertj$ tar -tvf MNP_2.6-4.tar.gz

    …

    drwxr-xr-x  0 hubertj PRINCETON\Domain Users     0 May  5 17:28 MNP/inst/

    drwxr-xr-x  0 hubertj PRINCETON\Domain Users     0 May  5 17:28 MNP/inst/doc/

    -rw-r--r--  0 hubertj PRINCETON\Domain Users 50180 May  5 17:28 MNP/inst/doc/MNP.Rnw

    -rw-r--r--  0 hubertj PRINCETON\Domain Users 878918 May  5 17:28 MNP/inst/doc/MNP.pdf

Thanks,

-Hubert

**Comment by kosukeimai** [comment]
Did you check the contents of the vignettes?

**Comment by HJ08003** [comment]
Here is the pdf file.
-Hubert

**Comment by HJ08003** [comment]
I compared the two pdf files, one built from my Github repo and the other built from your Github repo, they are same – numbers and figures.
Thanks,

-Hubert

**Pull request merged**
